"""Training loop for the Lorentz-constrained PINN (supervised + soft
constraint formulation).

For each regime (LT / WNL / UR) we train two models:
  - constrained:  L = lam_data L_data + lam_phys L_Lorentz
  - unconstrained:  L = lam_data L_data
The contrast between the two on the Lorentz invariant
gamma^2 - 1 - |P|^2 = 0 is the basis for Fig. 11.

Reference data is generated by scipy DOP853 (physics.solve_reference)
at machine precision (1e-13).  The PINN learns to interpolate the
reference at 500 anchor points and the Lorentz constraint regularizes
the prediction off the anchors.

For the trajectory in Fig. 10 we evaluate the trained constrained PINN
on a dense uniform 4000-point grid and compare against the reference.
"""

from __future__ import annotations

import json
import math
import time
from pathlib import Path

import numpy as np
import torch

from model import CoupledPINN, make_collocation
from physics import solve_reference


def compute_losses(model, t_data, y_data, t_col, y0_target,
                   lam_data, lam_ic, lam_phys, constrained: bool):
    y_pred = model(t_data)
    # Per-channel normalized data loss to balance contributions
    diff = (y_pred - y_data) / model.y_std
    L_d = (diff * diff).mean()
    # Soft IC
    y0_pred = model(torch.zeros(1, 1, device=t_col.device))
    diff_ic = (y0_pred - y0_target) / model.y_std
    L_ic = (diff_ic * diff_ic).mean()
    # Lorentz residual on collocation
    y_col = model(t_col)
    Px, Py, Pz, gamma = y_col[:, 0], y_col[:, 1], y_col[:, 2], y_col[:, 3]
    inv_residual = gamma * gamma - 1.0 - (Px * Px + Py * Py + Pz * Pz)
    L_lor = (inv_residual * inv_residual).mean()
    if constrained:
        loss = lam_data * L_d + lam_ic * L_ic + lam_phys * L_lor
    else:
        loss = lam_data * L_d + lam_ic * L_ic
    return loss, L_d, L_ic, L_lor


def train_one(a0_target, L, t_max, eta0,
              n_data=1000,
              n_collocation=2000,
              epochs_warm=6000,
              epochs_polish=4000,
              lam_data=1e2,
              lam_ic=1e3,
              lam_phys_warm=1e2,
              lam_phys_polish=1e6,
              constrained=True,
              device="cuda",
              seed=0):
    torch.manual_seed(seed)
    np.random.seed(seed)

    print("  computing reference ...")
    t_ref, y_ref = solve_reference(a0_target, L, eta0=eta0, t_max=t_max,
                                   n_dense=4000)
    idx = np.linspace(0, len(t_ref) - 1, n_data).astype(int)
    t_data = torch.tensor(t_ref[idx].reshape(-1, 1),
                          dtype=torch.float32, device=device)
    y_data = torch.tensor(y_ref[idx], dtype=torch.float32, device=device)
    y0_target = torch.tensor([[0.0, 0.0, 0.0, 1.0, eta0]],
                             dtype=torch.float32, device=device)

    # Per-channel mean and std from the reference for output normalization
    y_mean = tuple(float(v) for v in y_ref.mean(axis=0))
    y_std_raw = y_ref.std(axis=0)
    # Avoid zero std (in case some component is constant)
    y_std = tuple(float(max(s, 1e-3)) for s in y_std_raw)

    model = CoupledPINN(t_scale=t_max, y_mean=y_mean, y_std=y_std).to(device)
    t_col = torch.linspace(0.0, t_max, n_collocation,
                           device=device).unsqueeze(-1)
    history = []
    t0 = time.time()

    def adam_phase(epochs, lr_max, lr_min, lam_phys, label):
        optim = torch.optim.Adam(model.parameters(), lr=lr_max)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optim, T_max=epochs, eta_min=lr_min)
        for epoch in range(epochs):
            optim.zero_grad()
            loss, L_d, L_ic, L_lor = compute_losses(
                model, t_data, y_data, t_col, y0_target,
                lam_data, lam_ic, lam_phys, constrained=constrained)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optim.step()
            scheduler.step()
            if epoch % 500 == 0 or epoch == epochs - 1:
                history.append({
                    "stage": label, "epoch": epoch,
                    "L_data": float(L_d.detach()),
                    "L_ic": float(L_ic.detach()),
                    "L_lorentz": float(L_lor.detach()),
                    "loss": float(loss.detach()),
                    "wall": time.time() - t0,
                })
                print(f"  [{label} {epoch:5d}]  Ldata={float(L_d):.3e}  "
                      f"Lic={float(L_ic):.3e}  Llor={float(L_lor):.3e}")

    adam_phase(epochs_warm, 2e-3, 5e-5, lam_phys_warm, "warm")
    adam_phase(epochs_polish, 1e-4, 1e-6, lam_phys_polish, "polish")

    return model, history, (t_ref, y_ref)


def run_all(out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    # Short single-wavelength pulse for the PINN benchmark; physics is
    # qualitatively identical to the 5-wavelength chapter pulse but the
    # carrier oscillation count is small enough for a 4x64 tanh MLP
    # with Fourier-feature encoding to converge cleanly.
    L = 2.0 * math.pi
    eta0 = -3.0 * L
    t_max = 2.0 * abs(eta0) + 6.0 * L
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[device] {device}, L={L:.3f}, t_max={t_max:.3f}")

    # Regime-balanced lam_phys: the Lorentz residual (gamma^2 - 1 - |P|^2)
    # has dimensions of momentum-squared so it scales as gamma_max^4 across
    # regimes; the data loss is per-channel-normalized, so we counter-scale
    # lam_phys by 1/gamma_max^4 to keep the loss balance comparable.
    regimes = [
        ("LT", 0.85, 1e6),    # gamma_max ~ 1.2, scale ~ 1
        ("WNL", 8.5, 1e3),    # gamma_max ~ 20, scale ~ 1e5
        ("UR", 85.0, 1e1),    # gamma_max ~ 60, scale ~ 1e7
    ]
    runs = {}
    for tag, a0, lam_phys in regimes:
        print(f"\n=== {tag}  a0={a0}  constrained  lam_phys_polish={lam_phys} ===")
        m_c, h_c, ref_c = train_one(a0, L, t_max, eta0,
                                    constrained=True,
                                    lam_phys_polish=lam_phys,
                                    device=device, seed=0)
        torch.save(m_c.state_dict(), out_dir / f"pinn_{tag}_constrained.pt")
        with open(out_dir / f"history_{tag}_constrained.json", "w") as f:
            json.dump(h_c, f, indent=2)

        print(f"\n=== {tag}  a0={a0}  unconstrained ===")
        m_u, h_u, _ = train_one(a0, L, t_max, eta0,
                                constrained=False,
                                device=device, seed=0)
        torch.save(m_u.state_dict(), out_dir / f"pinn_{tag}_unconstrained.pt")
        with open(out_dir / f"history_{tag}_unconstrained.json", "w") as f:
            json.dump(h_u, f, indent=2)

        np.savez(out_dir / f"reference_{tag}.npz", t=ref_c[0], y=ref_c[1])
        runs[tag] = {"a0": a0, "L": L, "eta0": eta0, "t_max": t_max}

    with open(out_dir / "runs.json", "w") as f:
        json.dump(runs, f, indent=2)
    print(f"\nAll checkpoints saved in {out_dir}")


if __name__ == "__main__":
    run_all(Path(__file__).parent / "checkpoints")
